# Valepaska settings

# Screen
# ------
screen_width: 1600
screen_height: 900
sidebar_width: 150

# General things
# --------------
green: #35654d
grey: grey
font: 12

# Frames
# ------
opponent_height: 230
game_frame_pady: 300
game_frame_height: 250
card_frame_height: 250


# Hand cards
# ---------
# From each others
card_padx: 40
# From top of card frame, at least as much as elevate in card_settings.yml
card_pady: 50

# Card pile
# ---------
#How much cards are apart from each others
cardpile_offset: 8

# Paddings
cardpile_amount_padx: 60
cardpile_amount_pady: 0
cardpile_name_padx: 40
cardpile_name_pady: 0

# Game
# ----

# Names
deck_name: Deck
game_name: Game

game_frame_name_height: 40

# Relation to game frame
deck_pady: 0
deck_padx: 80
gamepile_pady: 20
gamepile_padx: 500

# Game pile hover
gamepile_hover_x: 14
gamepile_hover_y: 20

# Opponents
# ---------
# Opponents frame, should fit card and name
opponent_offset: 100
opponent_padx: 100
opponent_pady: 10